version: '3'
services:
  n8n:
    image: n8nio/n8n:1.59.0
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=n8nuser
      - N8N_BASIC_AUTH_PASSWORD=n8npassword
    networks:
      - custom_network
    volumes:
      - n8n_data:/home/node/.n8n

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    ports:
      - "4444:4444"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  n8n_data:

